### PR TITLE
March Release

### PR DESCRIPTION
**Pull request by steveyken**
@abhinav098 We discussed in scrum that these changes can be released to live right away.
- GCW-2446 Add Husky linters
- GCW-2226 Removal of braintree

### CODE REVIEW

**Comment by namrataukirde** [comment]
Good to go 👍

**Review by namrataukirde — APPROVED** [review]

**Comment by steveyken** [comment]
I'm Happy for abhinav to do the release

**Comment by namrataukirde** [comment]
Sure @steveyken :)

**Comment by namrataukirde** [comment]
It has a dependency on shared as well. 

@abulsayyad123 can clarify if it's okay to release without shared repo.

**Review by abhinav098 — APPROVED** [review]

**Comment by abulsayyad123** [comment]
Yes, it has dependency on shared as well. It has only difference of redirecting URL on GoodCity website. It will redirect to previous URL which we were using in case of iOS (https://www.goodcity.hk/get_involved_zh.html).

**Review by abulsayyad123 — APPROVED** [review]

**Review by abulsayyad123 — APPROVED** [review]

**Comment by abhinav098** [comment]
merged this to live

**Pull request merged**
